sonar.projectKey=isaac-checklist
sonar.projectName=isaac-checklist
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,setup-jest.ts,jest.config.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=src/main.ts,**/*.model.ts,setup-jest.ts,jest.config.js
